### ISSUE TITLE
how to use this with kaldi?

### ISSUE THREAD

**Issue by hasufell** [daanzu/speech-training-recorder#1]
i don't see any explanation on how to use this with kaldi and train the model

**Comment by daanzu** [comment]
This app is only for easily recording audio segments for training. The entire Kaldi training process is much more complicated, but I've been working on a pipeline using Docker that I hope to release soon.

**Comment by daanzu** [comment]
@hasufell I finally released some training scripts: https://github.com/daanzu/kaldi_ag_training
